version: '3'
services:
    nginx-cup:
        image: nginx
        container_name: nginx-cup
        restart: unless-stopped
        volumes:
            - ./routes/:/etc/nginx/conf.d/
        networks:
            default:
                ipv4_address: 172.2.30.1
    
    cup-side-default:
        build: ./cupside/
        container_name: cup-side-default
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.30.2
networks:
    default:
        external:
            name: deploy-pool_pool-network

