version: '3'
services:
    nginx-cup:
        image: nginx
        container_name: nginx-cup
        restart: unless-stopped
        volumes:
            - ./routes/nginx-cup/:/etc/nginx/conf.d/
        networks:
            default:
                ipv4_address: 172.3.30.1
    nginx-cup-ch:
        image: nginx
        container_name: nginx-cup-ch
        restart: unless-stopped
        volumes: 
           - ./routes/nginx-cup-ch/:/etc/nginx/conf.d/
        networks:
            default:
                ipv4_address: 172.2.35.1
    
    cup-side-default:
        build: 
            context: .
            dockerfile: cup-side-default.Dockerfile
        container_name: cup-side-default
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.3.30.2
    
    cup-side-default-ch:
        build:
            context: .
            dockerfile: cup-side-default-ch.Dockerfile
        container_name: cup-side-default-ch
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.3.35.2

networks:
    default:
        external:
            name: develop-pool2_pool-network

