version: '3'
services:
    nginx-cup:
        image: nginx
        container_name: nginx-cup
        restart: unless-stopped
        volumes:
            - ./routes/nginx-cup/:/etc/nginx/conf.d/
        networks:
            default:
                ipv4_address: 172.2.30.1
    nginx-cup-ch:
        image: nginx
        container_name: nginx-cup-ch
        restart: unless-stopped
        volumes: 
           - ./routes/nginx-cup-ch/:/etc/nginx/conf.d/
        networks:
            default:
                ipv4_address: 172.2.35.1
    
    cup-side-default:
        build: 
            context: .
            dockerfile: cup-side-default.Dockerfile
        container_name: cup-side-default
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.30.2
    cup-side-maeckes:
        build: 
            context: .
            dockerfile: cup-side-maeckes.Dockerfile
        container_name: cup-side-maeckes
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.30.3
    
    cup-side-okkid:
        build: 
            context: .
            dockerfile: cup-side-okkid.Dockerfile
        container_name: cup-side-okkid
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.30.4
    
    cup-side-default-ch:
        build:
            context: .
            dockerfile: cup-side-default-ch.Dockerfile
        container_name: cup-side-default-ch
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.35.2
    cup-side-oberrieden:
        build:
            context: .
            dockerfile: cup-side-oberrieden.Dockerfile
        container_name: cup-side-oberrieden
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.35.3


networks:
    default:
        external:
            name: pool-network

